### ISSUE TITLE
Cleaning up branches and branching model

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.AdminExperience.Extensions#577]
As I witnessed while working on #539, there is some debt in how branches are organised in this repository.

Here's what I think we should do:

1. Get rid of superfluous, stale branches
1. Remove `master`
1. Rename `development -> master` and make that the default brach
1. Adopt GitHub flow
   * work on feature branches as usual, merged directly to `master`
   * when ready to release we would tag `master` (next is `1.6.0`)
   * if necessary for regression, we could create a release branch to stabilize

**Comment by mitchelsellers** [comment]
I like this idea, but I think if we do this we should take a unified effort to make the structure the same across all of the projects so that we have consistency for community involvement.  

@dnnsoftware/tag any additional thoughts?

**Comment by tpluscode** [comment]
> take a unified effort to make the structure the same across all of the projects

Agreed 💯 percent. Like I said on Slack, there is no reinventing anything here. GitHub flow is now a pretty standard approach which, when agreed upon, would be exactly the same in all repos.
