### ISSUE TITLE
Drag and drop page on Tree View is not assign the page parent and presenting an error.

### ISSUE THREAD

**Issue by ricardodiasc** [dnnsoftware/Dnn.AdminExperience.Extensions#581]
## Description 

When the user try to move a page to be child of another page, ether by drag and drop or by selecting page parent on page detail, it presents an error.

## Steps to reproduce

- Login as host.
- From Persona Bar, Go to Content > Pages
- Select any page to be a child of Home by start dragging the page and try to drop on Home in treeview.

## Actual Result

Show an error on retrieving content

## Expected Result

Should be able to assign the dragged page as child of Home page.

## Affected version

* [x] 9.2.2
* [x] 9.2.1
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

## The source of this error when trying to move a page to be a child of another page

This is a defect included when trying to fix https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/560, some mistake was made because the activePage on tree view is diferent from the activePage on the main detail page.  The pull request https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/pull/580 has altered the name of this variable to avoid confusion in future mantainence.

**Comment by ricardodiasc** [comment]
Pull request on #580

**Comment by ricardodiasc** [comment]
@dnnsoftware/tag , this error also happens when on editing a page and try to select a page parent. The above pull request fix that problem too.

**Comment by tpluscode** [comment]
![image](https://user-images.githubusercontent.com/588128/41966842-71ab06dc-7a00-11e8-8c7e-ae5300cb139a.png)

Here's an screenshot of the error which appears in console

**Comment by ashishpd** [comment]
@ricardodiasc in order for the community to understand the importance of an issue, please mention whether this is new in the current release, i.e. is this a regression? If so, then this must be fixed in the upcoming release of 9.2.1. Can you provide more details in the issue description?

**Comment by ricardodiasc** [comment]
Hi @ashishpd, I updated the comment. Just to make it clear, this is a error introduced in 9.2.1 because of side effect when we tried to fix https://github.com/dnnsoftware/Dnn.AdminExperience.Extensions/issues/560. This is needed because the functionality of moving pages to new parents is not working at the moment on 9.2.1 and 9.2.2.

**Comment by pjkruger** [comment]
I did not see the previously logged issue. It is the same.
Is the plan to fix this in DNN9.2.1 and release a DNN9.2.1 RC1 as stated in the release notes, or is it going to be fixed in a later version of DNN?

**Comment by tpluscode** [comment]
At this point it's scheduled for the next release. cc @dnnsoftware/tag

**Comment by pjkruger** [comment]
So in DNN9.2.1 the only way to create a child page will be to use "Add Multiple Pages" with the ">" function. If you don't get it 100% correct the first time, then you must delete the entire tree and start again. There is no other way to create a single child page under an existing page or to move a page to another page.

If that is the case, then DNN9.2.1 is completely unusable imo.
