### ISSUE TITLE
(Non) developed modules

### ISSUE THREAD

**Issue by kurtwilbies** [dnnsoftware/Dnn.AdminExperience.Extensions#9]
Can you please give us a list of developed modules (Finished, production-ready, modules -> 100 percent OR partially developed (say for 40% etc...)), but also modules that will be developed in a vNext (next version). We, DNN partners and lovers, need more information to make (strong) business decisions and possibly help developing (submitting (new) pull requests). And what about a release date (BETA, RC) ???

**Comment by sleupold** [comment]
please provide your comment in the forums on dnnsoftware.com, thank you.
